import { Download, History } from 'lucide-react'
import type { CalendarFact, CalendarPlan, CalendarState } from '@/api/auditCalendar'
import { calendarStatuses, csvCell, timeLabel } from '@/lib/auditCalendar'

export function CalendarDataset({ state, onOpen, onRestore }: { state: CalendarState; onOpen: (date: string, start: number, plan?: CalendarPlan, fact?: CalendarFact) => void; onRestore: (plan: CalendarPlan) => void }) {
  const rows = [...state.plans.map(plan => ({ record: plan, plan, fact: undefined })), ...state.facts.map(fact => ({ record: fact, fact, plan: undefined }))].sort((a, b) => a.record.date.localeCompare(b.record.date) || a.record.start - b.record.start)
  function exportCSV() {
    const body = [['Слой', 'Дата', 'Начало', 'Минуты', 'Группа', 'Активность', 'Докладчик', 'Статус', 'Происхождение', 'Источник', 'Основание', 'Подтверждение'], ...rows.map(({ record: r, plan, fact }) => [plan ? 'План' : 'Факт', r.date, timeLabel(r.start), r.duration, state.groups.find(g => g.id === r.group_id)?.code, r.activity, state.members.find(m => m.user_id === r.speaker_id)?.full_name, calendarStatuses[plan ? plan.status : fact!.outcome], r.origin, plan?.source_id || '', fact?.reason || '', fact?.evidence || ''])].map(row => row.map(csvCell).join(';')).join('\r\n')
    const url = URL.createObjectURL(new Blob(['\uFEFF', body], { type: 'text/csv;charset=utf-8' }))
    const link = document.createElement('a'); link.href = url; link.download = 'audit-calendar.csv'; link.click()
    window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  return <section aria-label="Датасет"><header className="ac-section-head"><h2>Датасет <span className="ac-muted">{rows.length}</span></h2><button type="button" onClick={exportCSV}><Download size={16} />CSV</button></header><div className="ac-table-wrap"><table><thead><tr><th>Дата / время</th><th>Слой</th><th>Группа / активность / докладчик</th><th>Статус</th><th>Происхождение</th><th><span className="sr-only">Действия</span></th></tr></thead><tbody>{rows.map(({ record: r, plan, fact }) => <tr key={`${plan ? 'p' : 'f'}${r.id}`}><td>{r.date}<small>{timeLabel(r.start)}–{timeLabel(r.start + r.duration)}</small></td><td>{plan ? 'План' : 'Факт · неизменяемый'}</td><td><button type="button" className="ac-text-button" onClick={() => onOpen(r.date, r.start, plan, fact)}>{state.groups.find(g => g.id === r.group_id)?.code || 'Без группы'} · {r.activity || 'Без активности'}<small>{state.members.find(m => m.user_id === r.speaker_id)?.full_name || 'Докладчик не указан'}</small></button></td><td>{calendarStatuses[plan ? plan.status : fact!.outcome]}{plan && [...plan.issues, ...plan.warnings].map((issue, i) => <small key={i} className="ac-warning-text">{issue.message}</small>)}</td><td>{r.origin}{plan?.source_id && <small>{plan.source_id}</small>}{fact && <small>{fact.composition_unknown ? 'Состав не установлен' : 'Состав зафиксирован'}{!fact.plan_id ? ' · без связи с планом' : ''}</small>}</td><td>{plan?.source_id && plan.date < state.scope.today && state.actor.can_manage && !state.scope.archived && !state.facts.some(f => f.plan_id === plan.id) && <button type="button" onClick={() => onRestore(plan)}><History size={16} />Исторический факт</button>}</td></tr>)}</tbody></table></div>{!rows.length && <p className="ac-empty">В выбранном периоде записей нет.</p>}</section>
}
